var k101 = [

{ kanji:"日", yomimono:"にち", roman:"nichi", meaning:"day   " },
{ kanji:"本", yomimono:"ほん", roman:"hon", meaning:"book" },
{ kanji:"日本", yomimono:"にほん", roman:"nihon", meaning:"Japan" },
{ kanji:"山本", yomimono:"やまもと", roman:"yamamoto", meaning:"Surname" },
{ kanji:"日本語", yomimono:"にほんご", roman:"nihongo", meaning:"Japanese(language)" },
{ kanji:"大き　", yomimono:"おおき　", roman:"ooki", meaning:"big" },
{ kanji:"大学", yomimono:"だいがく", roman:"daigaku", meaning:"University" },
{ kanji:"生　", yomimono:"せい　", roman:"sei　", meaning:"life" },
{ kanji:"学生", yomimono:"がくせい ", roman:"gakusei", meaning:"student" },
{ kanji:"留学生", yomimono:"りゅうがくせい", roman:"ryuugakusei", meaning:"foreign student" },
{ kanji:"先", yomimono:"せん ", roman:"sen ", meaning:"previous" },
{ kanji:"先生", yomimono:"せんせい ", roman:"sensei ", meaning:"teacher" },
{ kanji:"先月", yomimono:"せんげつ ", roman:"sengetsu ", meaning:"last month" },
{ kanji:"先週", yomimono:"せんしゅう ", roman:"senshuu ", meaning:"last week" },
{ kanji:"何ですか", yomimono:"なんですか ", roman:"nandesuka ", meaning:"what is it?" },
{ kanji:"年", yomimono:"ねん ", roman:"nen ", meaning:"year" },
{ kanji:"行く", yomimono:"いく　", roman:"iku ", meaning:"to go" },
{ kanji:"旅行", yomimono:"りょこう ", roman:"ryokou ", meaning:"travel" },
{ kanji:"来る", yomimono:"くる ", roman:"kuru ", meaning:"To come" },
{ kanji:"来週", yomimono:"らいしゅう ", roman:"raishuu ", meaning:"next week" },
{ kanji:"見る", yomimono:"みる ", roman:"miru ", meaning:"to see/look at" },
{ kanji:"勉強", yomimono:"べんきょう ", roman:"benkyou ", meaning:"study" },
{ kanji:"強い", yomimono:"つよい ", roman:"tsuyoi ", meaning:"strong" },
{ kanji:"図書館", yomimono:"としょかん ", roman:"toshokan ", meaning:"library" },
{ kanji:"大山", yomimono:"おおやま ", roman:"ooyama ", meaning:"surname" },
{ kanji:"富士山", yomimono:"ふじさん ", roman:"fujisan ", meaning:"Mt Fuji" },
{ kanji:"山田", yomimono:"やまだ ", roman:"yamada ", meaning:"Surname" },
{ kanji:"田中", yomimono:"たなか ", roman:"tanaka ", meaning:"Surname" },
{ kanji:"本田", yomimono:"ほんだ ", roman:"honda ", meaning:"Surname" },
{ kanji:"日本人", yomimono:"にほんじん ", roman:"nihonjin ", meaning:"Japanese Person" },
{ kanji:"友だち", yomimono:"ともだち ", roman:"tomodachi ", meaning:"friend" },
{ kanji:"友子", yomimono:"ともこ ", roman:"tomoko ", meaning:"Name" },
{ kanji:"食べる", yomimono:"たべる ", roman:"taberu ", meaning:"to eat" },
{ kanji:"飲む", yomimono:"のむ ", roman:"nomu ", meaning:"to drink" },
{ kanji:"中", yomimono:"なか ", roman:"naka ", meaning:"inside, within" },
{ kanji:"中国語", yomimono:"ちゅうごくご", roman:"chuugokugo ", meaning:"Chinese language" },
{ kanji:"中山", yomimono:"なかやま ", roman:"nakayama ", meaning:"Surname" },
{ kanji:"百", yomimono:"ひゃく ", roman:"hyaku ", meaning:"hundred" },
{ kanji:"千", yomimono:"せん ", roman:"sen ", meaning:"thousand" },
{ kanji:"円", yomimono:"えん ", roman:"en 	", meaning:"yen" },
{ kanji:"買う", yomimono:"かう ", roman:"kau ", meaning:"to buy" },
{ kanji:"車", yomimono:"くるま ", roman:"kuruma ", meaning:"car" },
{ kanji:"電車　", yomimono:"でんしゃ ", roman:"densha ", meaning:"train(electric)" },
{ kanji:"話す", yomimono:"はなす ", roman:"hanasu ", meaning:"to talk" },
{ kanji:"電話", yomimono:"でんわ ", roman:"denwa ", meaning:"telephone" },
{ kanji:"英語", yomimono:"えいご ", roman:"eigo ", meaning:"English language" },
{ kanji:"英一", yomimono:"えいいち ", roman:"eiichi ", meaning:"Name" },
{ kanji:"万", yomimono:"まん ", roman:"man ", meaning:"ten thousand" },
{ kanji:"私", yomimono:"わたし ", roman:"watashi ", meaning:"prnoun for self me I" },
{ kanji:"名前", yomimono:"なまえ ", roman:"namae ", meaning:"name" },
{ kanji:"手", yomimono:"て ", roman:"te ", meaning:"hand" },
{ kanji:"右手", yomimono:"みぎて ", roman:"migite ", meaning:"right hand" },
{ kanji:"左手", yomimono:"ひだりて ", roman:"hidarite ", meaning:"left hand" },
{ kanji:"紙", yomimono:"かみ ", roman:"kami ", meaning:"paper" },
{ kanji:"手紙", yomimono:"てがみ ", roman:"tegami ", meaning:"letter" },
{ kanji:"書く", yomimono:"かく ", roman:"kaku ", meaning:"to write" },
{ kanji:"読む", yomimono:"よむ ", roman:"yomu ", meaning:"to read" },
{ kanji:"読書", yomimono:"どくしょ ", roman:"dokusho ", meaning:"reading(books)" },
{ kanji:"聞く", yomimono:"きく ", roman:"kiku ", meaning:"to listen" },
{ kanji:"新聞", yomimono:"しんぶん ", roman:"shinbun ", meaning:"newspaper" },
{ kanji:"東　", yomimono:"ひがし ", roman:"higashi ", meaning:"east" },
{ kanji:"東京", yomimono:"とうきょう ", roman:"toukyou ", meaning:"Tokyo" },
{ kanji:"京都", yomimono:"きょうと", roman:"kyouto ", meaning:"Kyoto" },
{ kanji:"京子", yomimono:"きょうこ", roman:"kyouko ", meaning:"Name" }


];