var k102 = [

{ kanji:"一日", yomimono:"ついたち", roman:"tsuitachi", meaning:"Day1" },
{ kanji:"二日", yomimono:"ふつか", roman:"futsuka", meaning:"Day2" },
{ kanji:"三日", yomimono:"みっか", roman:"mikka", meaning:"Day3" },
{ kanji:"四日", yomimono:"よっか", roman:"yokka", meaning:"Day4" },
{ kanji:"五日", yomimono:"いつか", roman:"itsuka", meaning:"Day5" },
{ kanji:"六日", yomimono:"むいか ", roman:"muika", meaning:"Day6" },
{ kanji:"七日", yomimono:"なのか", roman:"nanoka ", meaning:"Day7" },
{ kanji:"八日", yomimono:"ようか ", roman:"youka ", meaning:"Day8" },
{ kanji:"九日", yomimono:"ここのか ", roman:"kokonoka", meaning:"Day9" },
{ kanji:"十日　", yomimono:"とおか ", roman:"tooka ", meaning:"Day10" },
{ kanji:"十四日", yomimono:"じゅうよっか ", roman:"jyuuyokka", meaning:"Day14" },
{ kanji:"二十日", yomimono:"はつか", roman:"hatsuka ", meaning:"Day20" },
{ kanji:"日記", yomimono:"にっき", roman:"nikki", meaning:"diary" },
{ kanji:"日本", yomimono:"にほん", roman:"nihon", meaning:"Japan" },
{ kanji:"百", yomimono:"ひゃく", roman:"hyaku", meaning:"hundred" },
{ kanji:"千", yomimono:"せん", roman:"sen", meaning:"thousand" },
{ kanji:"万", yomimono:"まん", roman:"man", meaning:"Ten thousand" },
{ kanji:"円", yomimono:"えん", roman:"en", meaning:"Yen" },
{ kanji:"上", yomimono:"うえ", roman:"ue", meaning:"above" },
{ kanji:"中", yomimono:"なか", roman:"naka", meaning:"inside / within" },
{ kanji:"中国", yomimono:"ちゅうごく", roman:"cyuugoku", meaning:"China" },
{ kanji:"一日中", yomimono:"いちにちじゅう", roman:"ichinichijyuu", meaning:"throughout the day" },
{ kanji:"山下", yomimono:"やました", roman:"yamashita", meaning:"Surname" },
{ kanji:"山中", yomimono:"やまなか", roman:"yamanaka", meaning:"Surname" },
{ kanji:"中山", yomimono:"なかやま", roman:"nakayama", meaning:"Surname" },
{ kanji:"山本", yomimono:"やまもと", roman:"yamamoto", meaning:"Surname" },
{ kanji:"田中", yomimono:"たなか", roman:"tanaka", meaning:"Surname" },
{ kanji:"山田", yomimono:"やまだ", roman:"yamada", meaning:"Surname" },
{ kanji:"中田", yomimono:"なかだ", roman:"nakada", meaning:"Surname" },
{ kanji:"上田", yomimono:"うえだ", roman:"ueda", meaning:"Surname" },
{ kanji:"本田", yomimono:"ほんだ", roman:"honda", meaning:"Surname" },
{ kanji:"成田", yomimono:"なりた", roman:"narita", meaning:"Location" },
{ kanji:"大学", yomimono:"だいがく", roman:"daigaku", meaning:"university" },
{ kanji:"大山", yomimono:"おおやま", roman:"ooyama", meaning:"Surname" },
{ kanji:"大田", yomimono:"おおた", roman:"oota", meaning:"Surname" },
{ kanji:"大阪", yomimono:"おおさか", roman:"oosaka", meaning:"Location" },
{ kanji:"留学", yomimono:"りゅうがく", roman:"ryuugaku", meaning:"foreign study(study abroad)" },
{ kanji:"学生", yomimono:"がくせい", roman:"gakusei", meaning:"student" },
{ kanji:"大学生", yomimono:"だいがくせい", roman:"daigakusei", meaning:"university student" },
{ kanji:"留学生", yomimono:"りゅうがくせい", roman:"ryuugakusei", meaning:"foreign student" },
{ kanji:"先生", yomimono:"せんせい", roman:"sensei", meaning:"teacher" },
{ kanji:"今", yomimono:"いま", roman:"ima", meaning:"now" },
{ kanji:"今日", yomimono:"きょう", roman:"kyou", meaning:"today" },
{ kanji:"今日中", yomimono:"きょうじゅう", roman:"kyoujyuu", meaning:"throughout today" },
{ kanji:"年", yomimono:"ねん", roman:"nen", meaning:"year" },
{ kanji:"今年", yomimono:"ことし", roman:"kotoshi", meaning:"this year" },
{ kanji:"一年中", yomimono:"いちねんじゅう", roman:"ichinenjyuu", meaning:"throughout the year" },
{ kanji:"年上", yomimono:"としうえ", roman:"toshiue", meaning:"older" },
{ kanji:"年下", yomimono:"としした", roman:"toshishita", meaning:"shita" },
{ kanji:"行く", yomimono:"いく", roman:"iku", meaning:"to go" },
{ kanji:"旅行", yomimono:"りょこう", roman:"ryokou", meaning:"travel(abroad)" },
{ kanji:"来る", yomimono:"くる", roman:"kuru", meaning:"to come" },
{ kanji:"来年", yomimono:"らいねん", roman:"rainen", meaning:"next year" },
{ kanji:"手", yomimono:"て", roman:"te", meaning:"hand" },
{ kanji:"上手", yomimono:"じょうず", roman:"jyouzu", meaning:"good at something(skilled)" },
{ kanji:"下手", yomimono:"へた", roman:"heta", meaning:"bad at something(unskilled)" },
{ kanji:"紙", yomimono:"かみ", roman:"kami", meaning:"paper" },
{ kanji:"手紙", yomimono:"てがみ", roman:"tegami", meaning:"letter" },
{ kanji:"言う", yomimono:"いう", roman:"iu", meaning:"to speak / say" },
{ kanji:"日本語", yomimono:"にほんご", roman:"nihongo", meaning:"japanese language" },
{ kanji:"語学", yomimono:"ごがく", roman:"gogaku", meaning:"study of languages" },
{ kanji:"言語学", yomimono:"げんごがく", roman:"gengogaku", meaning:"linguistics" },
{ kanji:"中国語", yomimono:"ちゅうごくご", roman:"cyuugokugo", meaning:"Chinese language" },
{ kanji:"英語", yomimono:"えいご", roman:"eigo", meaning:"English language" },
{ kanji:"話す", yomimono:"はなす", roman:"hanasu", meaning:"to speak / talk / converse" },
{ kanji:"勉強", yomimono:"べんきょう", roman:"benkyou", meaning:"study" },
{ kanji:"友だち", yomimono:"ともだち", roman:"tomodachi", meaning:"friend" },
{ kanji:"友人", yomimono:"ゆうじん", roman:"yuujin", meaning:"friend" },
{ kanji:"子ども", yomimono:"こども", roman:"kodomo", meaning:"child" },
{ kanji:"友子", yomimono:"ともこ", roman:"tomoko", meaning:"Name" },
{ kanji:"英子", yomimono:"えいこ", roman:"eiko", meaning:"name" },
{ kanji:"好きだ", yomimono:"すきだ", roman:"sukida", meaning:"to like something" },
{ kanji:"大好き", yomimono:"だいすき", roman:"daisuki", meaning:"to really like something" },
{ kanji:"私", yomimono:"わたし", roman:"watashi", meaning:"pronoun for I self, me" },
{ kanji:"今週", yomimono:"こんしゅう", roman:"konshuu", meaning:"this week" },
{ kanji:"先週", yomimono:"せんしゅう", roman:"senshuu", meaning:"last week" },
{ kanji:"来週", yomimono:"らいしゅう", roman:"raishuu", meaning:"next week" },
{ kanji:"週末", yomimono:"しゅうまつ", roman:"shuumatsu", meaning:"weekend" },
{ kanji:"今週末", yomimono:"こんしゅうまつ", roman:"konshuumatsu", meaning:"this weekend" },
{ kanji:"年末", yomimono:"ねんまつ", roman:"nenmatsu", meaning:"end of the year" },
{ kanji:"専門", yomimono:"せんもん", roman:"senmon", meaning:"specialty" },
{ kanji:"専攻", yomimono:"せんこう", roman:"senkou", meaning:"major" },
{ kanji:"何時", yomimono:"なんじ", roman:"yomi", meaning:"What time?" },
{ kanji:"子どもの時", yomimono:"こどものとき", roman:"yomi", meaning:"When I was a kid/child" },
{ kanji:"日時", yomimono:"にちじ", roman:"yomi", meaning:"date and time" },
{ kanji:"何分", yomimono:"なんふん", roman:"yomi", meaning:"What minute of the hour / how many minutes" },
{ kanji:"分かる", yomimono:"わかる", roman:"yomi", meaning:"To understand, comprehend, know." },
{ kanji:"半", yomimono:"はん", roman:"yomi", meaning:"half" },
{ kanji:"半日", yomimono:"はんにち", roman:"yomi", meaning:"half a day" },
{ kanji:"半年", yomimono:"はんねん", roman:"yomi", meaning:"half a year" },
{ kanji:"半分", yomimono:"はんぶん", roman:"yomi", meaning:"half (in general)" },
{ kanji:"日曜日", yomimono:"にちようび", roman:"yomi", meaning:"Sunday" },
{ kanji:"今月", yomimono:"こんげつ", roman:"yomi", meaning:"This month" },
{ kanji:"先月", yomimono:"せんげつ", roman:"yomi", meaning:"last month" },
{ kanji:"来月", yomimono:"らいげつ", roman:"yomi", meaning:"next month" },
{ kanji:"何月", yomimono:"なんがつ", roman:"yomi", meaning:"what month?" },
{ kanji:"月曜日", yomimono:"げつようび", roman:"yomi", meaning:"Monday" },
{ kanji:"火曜日", yomimono:"かようび", roman:"yomi", meaning:"Tuesday" },
{ kanji:"水曜日", yomimono:"すいようび", roman:"yomi", meaning:"Wednesday" },
{ kanji:"水　", yomimono:"みず", roman:"yomi", meaning:"water" },
{ kanji:"木", yomimono:"き", roman:"yomi", meaning:"tree / wood" },
{ kanji:"木曜日", yomimono:"もくようび", roman:"yomi", meaning:"Thursday" },
{ kanji:"お金", yomimono:"おかね", roman:"yomi", meaning:"monday" },
{ kanji:"金曜日", yomimono:"きにょうび", roman:"yomi", meaning:"Friday" },
{ kanji:"金田", yomimono:"かねだ", roman:"yomi", meaning:"Name" },
{ kanji:"土曜日", yomimono:"どようび", roman:"yomi", meaning:"Saturday" },
{ kanji:"本土", yomimono:"ほんど", roman:"yomi", meaning:"Mainland" },
{ kanji:"前", yomimono:"まえ", roman:"yomi", meaning:"in front of, before." },
{ kanji:"前田", yomimono:"まえだ", roman:"yomi", meaning:"Name" },
{ kanji:"手前", yomimono:"てまえ", roman:"yomi", meaning:"this side of" },
{ kanji:"後ろ", yomimono:"うしろ", roman:"yomi", meaning:"Behind, in back of" },
{ kanji:"後　", yomimono:"あと", roman:"yomi", meaning:"following, after, succeding, sequel" },
{ kanji:"午前", yomimono:"ごぜん", roman:"yomi", meaning:"A.M. (before noon)" },
{ kanji:"午後", yomimono:"ごご", roman:"yomi", meaning:"P.M. (after noon)" },
{ kanji:"会う", yomimono:"あう", roman:"yomi", meaning:"to meet" },
{ kanji:"会話", yomimono:"かいわ", roman:"yomi", meaning:"conversation" },
{ kanji:"英会話", yomimono:"えいかいわ", roman:"yomi", meaning:"English conversation" },
{ kanji:"勉強会", yomimono:"べんきょうかい", roman:"yomi", meaning:"study meeting" },
{ kanji:"大会", yomimono:"たいかい", roman:"yomi", meaning:"contest / tournament" },
{ kanji:"学会", yomimono:"がっかい", roman:"yomi", meaning:"academic conference" },
{ kanji:"休む", yomimono:"やすむ", roman:"yomi", meaning:"to rest, take time off, be absent, miss" },
{ kanji:"朝　", yomimono:"あさ", roman:"yomi", meaning:"morning" },
{ kanji:"朝ごはん", yomimono:"あさごはん", roman:"yomi", meaning:"breakfast" },
{ kanji:"今朝", yomimono:"けさ", roman:"yomi", meaning:"this morning" },
{ kanji:"昼", yomimono:"ひる", roman:"yomi", meaning:"noon" },
{ kanji:"昼休み", yomimono:"ひるやすみ", roman:"yomi", meaning:"lunch break" },
{ kanji:"晩", yomimono:"ばん", roman:"yomi", meaning:"evening" },
{ kanji:"今晩", yomimono:"こんばん", roman:"yomi", meaning:"this evening" },
{ kanji:"晩ごはん", yomimono:"ばんごはん", roman:"yomi", meaning:"dinner" },
{ kanji:"食べる", yomimono:"たべる", roman:"yomi", meaning:"to eat" },
{ kanji:"食べ物", yomimono:"たべもの", roman:"yomi", meaning:"food" },
{ kanji:"飲む", yomimono:"のむ", roman:"yomi", meaning:"to drink" },
{ kanji:"飲み物", yomimono:"のみもの", roman:"yomi", meaning:"drinks" },
{ kanji:"毎日", yomimono:"まいにち", roman:"yomi", meaning:"every day" },
{ kanji:"毎週", yomimono:"まいしゅう", roman:"yomi", meaning:"every week" },
{ kanji:"毎月", yomimono:"まいつき", roman:"yomi", meaning:"every month" },
{ kanji:"毎年", yomimono:"まいとし", roman:"yomi", meaning:"every year" },
{ kanji:"見る", yomimono:"みる", roman:"yomi", meaning:"to see, look at, watch" },
{ kanji:"習う", yomimono:"ならう", roman:"yomi", meaning:"to learn, take lessons" },
{ kanji:"学習", yomimono:"がくしゅう", roman:"yomi", meaning:"learning, study" },
{ kanji:"練習", yomimono:"れんしゅう", roman:"yomi", meaning:"practice, exercise" },
{ kanji:"復習", yomimono:"ふくしゅう", roman:"yomi", meaning:"review" },
{ kanji:"学校", yomimono:"がっこう", roman:"yomi", meaning:"school" },
{ kanji:"中学校", yomimono:"ちゅうがっこう", roman:"yomi", meaning:"junior high school" },
{ kanji:"高校", yomimono:"こうこう", roman:"yomi", meaning:"high school" },
{ kanji:"専門学校", yomimono:"せんもんがっこう", roman:"yomi", meaning:"professional, trade school, trade school" },
{ kanji:"電話", yomimono:"でんわ", roman:"yomi", meaning:"telephone, phone call" },
{ kanji:"車", yomimono:"くるま", roman:"yomi", meaning:"car" },
{ kanji:"東　", yomimono:"ひがし", roman:"yomi", meaning:"east" },
{ kanji:"東京", yomimono:"とうきょう", roman:"yomi", meaning:"Tokyo" },
{ kanji:"京子", yomimono:"きょうこ", roman:"yomi", meaning:"Name" },
{ kanji:"京都", yomimono:"きょうと", roman:"yomi", meaning:"Kyoto" },
{ kanji:"東京大学", yomimono:"とうきょうだいがく", roman:"yomi", meaning:"Tokyo University (specific place)" }



];